# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      cd C:\Program Files (x86)\SmartBear\SoapUI-5.5.0\bin
      testrunner.bat -j "F:\SOAPUI\Project\Currency-Convertor-soapui-project.xml"