# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: CmdLine@2
  inputs:
    script: |

      cd C:\Program Files (x86)\SmartBear\SoapUI-5.5.0\bin
      

      cd /d %SOAPUI_HOME%..\bin

      echo %JAVA_HOME%
      testrunner.bat "F:\SOAPUI\Project\Currency-Convertor-soapui-project.xml"
      echo Hello world

